const TYPES = {
    SET_VIEW: "SET_VIEW",
    SET_AGE: "SET_AGE",
    SET_PREGNANT: "SET_PREGNANT",
    SET_SYMPTOM: "SET_SYMPTOM",
    SET_DATA: "SET_DATA",
    SET_DRUG:"SET_DRUG",
    CLEAR_ALL:"CLEAR_ALL",
    SET_RASH_RESULT: "SET_RASH_RESULT",
    SET_GENDER: "SET_GENDER",
    SET_PAIN_RESULT:"SET_PAIN_RESULT",
}

module.exports = TYPES